### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by rross101** [human-substrate/Problems#3]
Love this idea and happy to get stuck in. What's the best way to do that constructively?

**Comment by JustBen8** [comment]
In the substrate article at the bottom Daniel mentions 
If you are interested in contributing, you can do so through [the Github projects themselves](https://github.com/human-substrate?), or you can connect with us directly.

https://danielmiessler.com/p/introducing-substrate

**Comment by rross101** [comment]
Great, I think we need a README with step by step guide for someone thinking about how to make additions as discussed in #5.

**Comment by danielmiessler** [comment]
Agreed, I'll create one.
