### ISSUE TITLE
Interface to Enter new problems

### ISSUE THREAD

**Issue by shahiryar** [human-substrate/Problems#5]
There should be an easy to access interface where a lay-/non-technical person could add problems.

Otherwise, there is a risk of substantively limited sample of problems.

**Comment by rross101** [comment]
Yes and in the meantime some brief notes about how to add a problem to the text file - presumably:

- fork the  repository
- guidance on the fields to add and some guidance on word count and numbering as per #6 
- pull request to merge those changes back in

**Comment by danielmiessler** [comment]
Yes, this is a very good idea, and currently in the works. Thank you.
