### ISSUE TITLE
Problem IDs

### ISSUE THREAD

**Issue by shahiryar** [human-substrate/Problems#6]
How are the problem ideas identify a problem; is there an underlying pattern or order?

For example: if there are categories with ids and subcategories that are used in creating ids so that the problem ids convey a meaning.
For example:
Cat1 has id C23
Cat2 has id C54

then a problem belonging to both the categories will have id
PID-C2354-P91

**Comment by danielmiessler** [comment]
There's no hierarchy right now, no. They're just random IDs.
